### ISSUE TITLE
Req: XPI-file: Non-cryptic name

### ISSUE THREAD

**Issue by Jonta** [whitty/tabreaper#14]
Right now, going to `~/.mozilla/firefox/[profile-ID]/extensions/`, this extension is identified by an opaque hex-string

An example of an extension that has a clear name, is HTTPS Everywhere: https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/

=)

**Comment by whitty** [comment]
Hi, if you know anything more than I do about the ID field and if it can be changed please let me know.

The ID is assigned by mozilla and cannot be changed without losing the identity of the addon.

https://extensionworkshop.com/documentation/develop/extensions-and-the-add-on-id/#When_do_you_need_an_add-on_ID

It is possible that I misread how to use the ID and have conflated the UUID with the ID, but looking through my profiles I think I'm not the only extension that has done so.  Possibly the instructions at some point in time were different.

FYI what I upload to the store is called "tab_reaper-0.98.zip", addons.mozilla.org creates the final XPI name

**Comment by whitty** [comment]
See also: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings which suggest UUID are preferable in some cases.

**Comment by whitty** [comment]
Closing as stale, please comment if you have more information
