### ISSUE TITLE
Regex matching

### ISSUE THREAD

**Issue by Kixunil** [whitty/tabreaper#18]
First of all, thanks a lot for this great extension!

In some cases it'd be really useful to be able to regex match. E.g. if I want to close all tabs that show lists of GH issues rather than specific issues I'd like to specify `github\.com/issues$` to not match path after the last `/`. I'm pretty sure this would be useful for tons of other things. I think the simplest version is to just have a checkbox "Regex matching" which toggles the mode.

**Comment by whitty** [comment]
I'm wondering if "whole match" for URLs (implicitly end-of-URL match) or "whole word" match for title mode would be simpler and do the job for non-programming types.  Wondering if I should put regex matching behind a preference to enable (and leave some way to guide you to it.

**Comment by Kixunil** [comment]
Whole match wouldn't be helpful because the repositories differ. It could help some people but really, that's almost the same as duplicates. I also don't think having regexes exposed directly is a bad UX for users that don't know them - they'll just ignore it. I've seen many programs do this.

**Comment by whitty** [comment]
I've just released version 1.3.0 with regex support - I'm looking at reworking it in the future since the check-boxes are starting to take up some real-estate.

**Comment by Kixunil** [comment]
Thanks a lot! I think three checkboxes are still fine.
